### ISSUE TITLE
SequelizeAccessDeniedError:

### ISSUE THREAD

**Issue by Aquilafire** [ZyC0R3/RitaBot#124]
i have a this problem on os ubuntu 16.04

Unhandled Rejection
Caused By:
SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: NO)
    at /tmp/RitaBot/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:125:19
    at tryCatcher (/tmp/RitaBot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
Unhandled Rejection
Caused By:
SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: NO)
    at /tmp/RitaBot/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:125:19
    at tryCatcher (/tmp/RitaBot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
Unhandled Rejection
Caused By:
SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: NO)
    at /tmp/RitaBot/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:125:19
    at tryCatcher (/tmp/RitaBot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/tmp/RitaBot/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/tmp/RitaBot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
hook.send error:
DiscordAPIError: 405: Method Not Allowed
hook.send error:
DiscordAPIError: 405: Method Not Allowed
hook.send error:
DiscordAPIError: 405: Method Not Allowed
hook.send error:
DiscordAPIError: 405: Method Not Allowed

**Comment by ZyC0R3** [comment]
This seems to be a DB Authentication error, Check the password for the DB and try again,.
