### ISSUE TITLE
botSend error

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/RitaBot#140]
**Describe the bug**
When ever you use a command that has a variable responce that calls send.js it will error out.

**To Reproduce**
Use any command that calls send.js

**Expected behaviour**
No Error

**Error Message from Webhook**
Unhandled Rejection
Caused By:
TypeError: botSend is not a function
    at Object.embed (/app/src/commands/settings.js:231:17)
    at getSettings (/app/src/commands/settings.js:283:41)
    at Object.module.exports.run [as settings] (/app/src/commands/settings.js:64:4)
    at /app/src/commands/args.js:238:29
    at /app/src/core/db.js:333:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by ZyC0R3** [comment]
Resolved
