### ISSUE TITLE
data.message undefined

### ISSUE THREAD

**Issue by ArtanisTheOne** [ZyC0R3/RitaBot#147]
**Describe the bug**
Data.message flickering

**To Reproduce**
1. Import message from message.js into send.js
2. Click on breakpoint in the function sendWebhookMessage and create another one outside of the function
3. Scroll down to sendWebhookMessage and replace data.bot.username with data.message.author.username
4. Let it play out and you see data.message is not defined when it stops in the function but then when breakpoint stops outside the function it is defined with the values we need.

**Expected behaviour**
data.message to be defined at all times and to send correctly for us to be able to use it's values.

**Error Message from Webhook**
```
Unhandled Rejection
Caused By:
TypeError: Cannot read property 'author' of undefined
    at sendSoloImage (c:\RitaDevelopment\RitaBot\src\core\send.js:445:42)
    at sendWebhookMessage (c:\RitaDevelopment\RitaBot\src\core\send.js:476:22)
    at c:\RitaDevelopment\RitaBot\src\core\send.js:351:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Screenshots**
https://drive.google.com/file/d/1_F_wGOWK9Jligh0EWO1S-6vMNpjvHbb5/view?usp=sharing  
Screen cast of me going through the issue,   turn off volume as there is static.

**Additional context**
We need to use data.message to have single image attachments send with author name instead of bot name.

**Comment by ArtanisTheOne** [comment]
Moved data.message values to message by making message var global.
