### ISSUE TITLE
Not Connecting to Database

### ISSUE THREAD

**Issue by warlock1337-1337** [ZyC0R3/RitaBot#232]
Bot not responding, but instead giving error below everytime, I try to type t! help or any other commands.

Unhandled Rejection
Caused By:
SequelizeConnectionError: no pg_hba.conf entry for host "CENSORED", user "CENSORED", database "CENSORED", SSL off
    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:296:19)
    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:316:19)
    at Connection.emit (events.js:315:20)
    at /app/node_modules/pg/lib/connection.js:109:12
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)

**Comment by ArtanisTheOne** [comment]
Hm it seems to be an annoying Heroku error, I will defenitely look into this

**Comment by ArtanisTheOne** [comment]
Seem to have find a fix in [sequelize](https://github.com/sequelize/sequelize/issues/956#issuecomment-147745033) which only needs to be added in db.js (will work on this today)

**Comment by ArtanisTheOne** [comment]
Completed,  please update your fork and deploy again in Heroku. Error has been resolved. @warlock1337-1337 

Apologies for the lateness, forgot to close this
